name: Sync Upstream WebClients Repository
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive

      - name: Setup git bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check for Upstream Changes
        run: |
          # get latest commit hash from upstream
          COMMIT=$(curl -s https://api.github.com/repos/ProtonMail/WebClients/commits/main | jq -r '.sha')
          # get commit hash from submodule
          cd WebClients
          SUBMODULE_COMMIT=$(git rev-parse HEAD)
          cd ..

          if [ "$COMMIT" != "$SUBMODULE_COMMIT" ]; then
            echo "Update Submodule to latest commit $COMMIT"
            git submodule update --remote
            git add WebClients
            git commit -m "chore(WebClients): sync with upstream"
            git push
          else
            echo "Upstream is up to date"
          fi